version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
      - "python"
      - "dependencies"
  commit-message:
      prefix: "pip prod"
      include: "scope"
