- repo: local

  hooks:
    - id: bandit
      name: bandit
      entry: bandit
      language: system
      types: [python]
      args: [--line-length=200, --target-version=py39]

    - id: autoflake
      name: autoflake
      entry: autoflake
      language: system
      types: [python]
      args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]

    - id: pyupgrade
      name: pyupgrade
      entry: pyupgrade
      language: system
      types: [python]
      args: [--py39-plus]

    - id: reorder-python-imports
      name: reorder-python-imports
      entry: reorder-python-imports
      language: system
      types: [python]
      args: [--py39-plus]

    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: [--max-line-length=200]
