[tool.poetry]
name = "scanning-with-python"
version = "0.1.0"
description = "Building a Scanning Tool Using Python"
authors = ["Searge"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
rich = "^12.5"
urllib3 = "^1.26"
scapy = "^2.4.5"
click = "^8.1.3"
asyncio = "^3.4.3"

[tool.poetry.dev-dependencies]
jupyter = "^1.0.0"

autopep8 = "^1.5.7"
mypy = "^0.961"
wemake-python-styleguide = "^0.16.1"

pre-commit = "^2.20.0"
bandit = "^1.7.4"
autoflake = "^1.4"
pyupgrade = "^2.37.1"
reorder-python-imports = "^3.8.2"
pycodestyle = "^2.8.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.nitpick]
style = [
  "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/flake8.toml",
  "https://raw.githubusercontent.com/wemake-services/wemake-python-styleguide/master/styles/isort.toml"
]
